"""fix relationship between order and organisation 3

Revision ID: 186c14f5e040
Revises: 7a20d58b1c81
Create Date: 2023-06-19 01:12:05.803438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186c14f5e040'
down_revision = '7a20d58b1c81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
