"""remove uniqueness for organisation name

Revision ID: 42d94e9d825e
Revises: f5e17b120a95
Create Date: 2023-06-19 17:59:25.632879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d94e9d825e'
down_revision = 'f5e17b120a95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organisations_Name', table_name='organisations')
    op.create_index(op.f('ix_organisations_Name'), 'organisations', ['Name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisations_Name'), table_name='organisations')
    op.create_index('ix_organisations_Name', 'organisations', ['Name'], unique=False)
    # ### end Alembic commands ###
