"""fix relationship between order and organisation

Revision ID: 4d3cb6958088
Revises: c8d9d44c36b4
Create Date: 2023-06-19 01:08:41.135657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3cb6958088'
down_revision = 'c8d9d44c36b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
