"""modify relationship between orgs and orders

Revision ID: 5c8a39f2df7d
Revises: 93f72a4b23fd
Create Date: 2023-06-19 12:37:57.465674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8a39f2df7d'
down_revision = '93f72a4b23fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
