"""fix relationship between order and organisation 2

Revision ID: 7a20d58b1c81
Revises: 4d3cb6958088
Create Date: 2023-06-19 01:11:02.806964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a20d58b1c81'
down_revision = '4d3cb6958088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
