"""undo

Revision ID: 93f72a4b23fd
Revises: 186c14f5e040
Create Date: 2023-06-19 01:13:03.129467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f72a4b23fd'
down_revision = '186c14f5e040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
