"""first migration

Revision ID: a836e39c3494
Revises: 
Create Date: 2023-06-17 21:50:21.250741

"""
from alembic import op
import sqlalchemy as sa
from src.database.models.order import ProductType

# revision identifiers, used by Alembic.
revision = 'a836e39c3494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Type', sa.Enum('BUYER', 'SELLER', name='organisationtypeenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_Name'), 'organisations', ['Name'], unique=True)
    op.create_index(op.f('ix_organisations_Type'), 'organisations', ['Type'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(), nullable=False),
    sa.Column('Variety', sa.String(), nullable=False),
    sa.Column('Packaging', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_Category'), 'products', ['Category'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Enum('BUY', 'SELL', name='ordertypeenum'), nullable=False),
    sa.Column('References', sa.Integer(), nullable=True),
    sa.Column('Products', sa.ARRAY(ProductType()), nullable=False),
    sa.Column('Organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['References'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_Type'), 'orders', ['Type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_Type'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_Category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organisations_Type'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_Name'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
