"""add hybrid property Products to Organisation

Revision ID: c8d9d44c36b4
Revises: a836e39c3494
Create Date: 2023-06-18 23:52:11.453746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d9d44c36b4'
down_revision = 'a836e39c3494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
