"""make orders.product nullable, and add uniqueness contraints to org name and type

Revision ID: da7701d1b980
Revises: 5c8a39f2df7d
Create Date: 2023-06-19 17:54:15.683484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da7701d1b980'
down_revision = '5c8a39f2df7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'Products',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.create_unique_constraint(None, 'organisations', ['Name', 'Type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations', type_='unique')
    op.alter_column('orders', 'Products',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###
